# Generated by Django 5.0.1 on 2024-02-06 09:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("article", "0004_comment"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="comment",
            options={"ordering": ["-comment_date"]},
        ),
    ]
